In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pulsestreamer as pstr
ip = '192.168.1.76'
ps = pstr.PulseStreamer(ip)

Connect to Pulse Streamer via JSON-RPC.
IP / Hostname: 192.168.1.76
Pulse Streamer 8/2 firmware: v1.6.3
Client software: v1.7.0
Your client software is more up to date than the Pulse Streamer 8/2 firmware. We recommend updating the firmware of your Pulse Streamer 8/2.
For detailed information visit https://www.swabianinstruments.com/pulse-streamer-8-2/downloads/ or contact support@swabianinstruments.com


In [11]:
# A pulse with 10µs HIGH and 30µs LOW levels
pattern = [(10000, 1), (10000, 0)]
sequence = ps.createSequence()
# Create sequence and assign pattern to digital channel 0
sequence.setDigital(0, pattern)

n_runs = pstr.PulseStreamer.REPEAT_INFINITELY
ps.stream(sequence, n_runs)

In [12]:
ps.constant(([0],0,0))

In [1]:
from ni_photonCounting import NIDAQ_PhotonCounter

In [15]:
rate = 100
numSamples = 10
with NIDAQ_PhotonCounter() as daq:
    counts = daq.readCtrs_multiRead_intClk(rate, numSamples)
print(counts)

[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]


DAQ connetcs to pulsestreamer. Next: connect with inserv


Go to inserv.py and add the DAQ

To test, run inserv.py and send commands.  
Open python with: Python  

```python
from nspyre import InstrumentGateway
gw = InstrumentGateway()
gw.connect()
gw.nidaq
<nspyre.instrument.gateway.InstrumentGatewayDevice object at 0x000002A5F19BD1D0>
rate = 100
samples = 10
counts = gw.nidaq.readCtrs_multiRead_intClk(rate,samples)
print(counts)
gw.disconnect()
```